<?php
/**
 * InstallationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Chabok\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Chabok Push
 *
 * Integrate your app with Chabok messaging & push api seamlessly
 *
 * OpenAPI spec version: 1.21.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Chabok\Client;

/**
 * InstallationTest Class Doc Comment
 *
 * @category    Class */
// * @description Installation
/**
 * @package     Chabok\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InstallationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Installation"
     */
    public function testInstallation()
    {
    }

    /**
     * Test attribute "launch_count"
     */
    public function testPropertyLaunchCount()
    {
    }

    /**
     * Test attribute "launch_time"
     */
    public function testPropertyLaunchTime()
    {
    }

    /**
     * Test attribute "os_version"
     */
    public function testPropertyOsVersion()
    {
    }

    /**
     * Test attribute "device_model"
     */
    public function testPropertyDeviceModel()
    {
    }

    /**
     * Test attribute "connection"
     */
    public function testPropertyConnection()
    {
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
    }

    /**
     * Test attribute "on_at"
     */
    public function testPropertyOnAt()
    {
    }

    /**
     * Test attribute "is_new"
     */
    public function testPropertyIsNew()
    {
    }

    /**
     * Test attribute "notification_settings"
     */
    public function testPropertyNotificationSettings()
    {
    }

    /**
     * Test attribute "app_id"
     */
    public function testPropertyAppId()
    {
    }

    /**
     * Test attribute "app_version"
     */
    public function testPropertyAppVersion()
    {
    }

    /**
     * Test attribute "badge"
     */
    public function testPropertyBadge()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "device_token"
     */
    public function testPropertyDeviceToken()
    {
    }

    /**
     * Test attribute "device_type"
     */
    public function testPropertyDeviceType()
    {
    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "subscriptions"
     */
    public function testPropertySubscriptions()
    {
    }

    /**
     * Test attribute "time_zone"
     */
    public function testPropertyTimeZone()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }
}
