<?php
/**
 * MessageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Chabok Push
 *
 * Integrate your app with Chabok messaging & push api seamlessly
 *
 * OpenAPI spec version: 1.19.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MessageTest Class Doc Comment
 *
 * @category    Class */
// * @description Message
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MessageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Message"
     */
    public function testMessage()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "content_type"
     */
    public function testPropertyContentType()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "delivered"
     */
    public function testPropertyDelivered()
    {
    }

    /**
     * Test attribute "seen"
     */
    public function testPropertySeen()
    {
    }

    /**
     * Test attribute "dismiss"
     */
    public function testPropertyDismiss()
    {
    }

    /**
     * Test attribute "stateful"
     */
    public function testPropertyStateful()
    {
    }

    /**
     * Test attribute "live"
     */
    public function testPropertyLive()
    {
    }

    /**
     * Test attribute "in_app"
     */
    public function testPropertyInApp()
    {
    }

    /**
     * Test attribute "publish_id"
     */
    public function testPropertyPublishId()
    {
    }

    /**
     * Test attribute "c_id"
     */
    public function testPropertyCId()
    {
    }

    /**
     * Test attribute "track_id"
     */
    public function testPropertyTrackId()
    {
    }

    /**
     * Test attribute "cip"
     */
    public function testPropertyCip()
    {
    }
}
