<?php
/**
 * PushTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Chabok\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Chabok Push
 *
 * Integrate your app with Chabok messaging & push api seamlessly
 *
 * OpenAPI spec version: 1.21.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Chabok\Client;

/**
 * PushTest Class Doc Comment
 *
 * @category    Class */
// * @description Push
/**
 * @package     Chabok\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PushTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Push"
     */
    public function testPush()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "track_id"
     */
    public function testPropertyTrackId()
    {
    }

    /**
     * Test attribute "in_app"
     */
    public function testPropertyInApp()
    {
    }

    /**
     * Test attribute "live"
     */
    public function testPropertyLive()
    {
    }

    /**
     * Test attribute "use_as_alert"
     */
    public function testPropertyUseAsAlert()
    {
    }

    /**
     * Test attribute "alert_text"
     */
    public function testPropertyAlertText()
    {
    }

    /**
     * Test attribute "ttl"
     */
    public function testPropertyTtl()
    {
    }

    /**
     * Test attribute "fallback"
     */
    public function testPropertyFallback()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "notification"
     */
    public function testPropertyNotification()
    {
    }

    /**
     * Test attribute "idr"
     */
    public function testPropertyIdr()
    {
    }

    /**
     * Test attribute "silent"
     */
    public function testPropertySilent()
    {
    }

    /**
     * Test attribute "content_binary"
     */
    public function testPropertyContentBinary()
    {
    }

    /**
     * Test attribute "content_type"
     */
    public function testPropertyContentType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }
}
