<?php
/**
 * InstallationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Chabok Push
 *
 * Integrate your app with Chabok messaging & push api seamlessly
 *
 * OpenAPI spec version: 1.19.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * InstallationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InstallationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for installationAddTag
     *
     * Add tag to all devices of a user.
     *
     */
    public function testInstallationAddTag()
    {
    }

    /**
     * Test case for installationFetchById
     *
     * Find device installation data by installationId.
     *
     */
    public function testInstallationFetchById()
    {
    }

    /**
     * Test case for installationFetchByUserId
     *
     * Find devices of a specific user.
     *
     */
    public function testInstallationFetchByUserId()
    {
    }

    /**
     * Test case for installationGroupBySubscription
     *
     * List of unique channel names.
     *
     */
    public function testInstallationGroupBySubscription()
    {
    }

    /**
     * Test case for installationRemoveTag
     *
     * Remove a tag from devices of a UserId.
     *
     */
    public function testInstallationRemoveTag()
    {
    }

    /**
     * Test case for installationTags
     *
     * List of unique tag names.
     *
     */
    public function testInstallationTags()
    {
    }
}
