<?php
/**
 * PushApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Chabok\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Chabok Push
 *
 * Integrate your app with Chabok messaging & push api seamlessly
 *
 * OpenAPI spec version: 1.21.4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Chabok\Client;

use \Chabok\Client\Configuration;
use \Chabok\Client\ApiClient;
use \Chabok\Client\ApiException;
use \Chabok\Client\ObjectSerializer;

/**
 * PushApiTest Class Doc Comment
 *
 * @category Class
 * @package  Chabok\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PushApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for pushByQuery
     *
     * Push a text message to a segment of devices.
     *
     */
    public function testPushByQuery()
    {
    }

    /**
     * Test case for pushToUsers
     *
     * Push multiple text messages to users.
     *
     */
    public function testPushToUsers()
    {
    }
}
